name: Production Deploy
 
on:
    push:
        branches:
        - main
    
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: 2424833f/go_docker_mainp:latest

      - name: Check out the code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            REMOTE_HOST: ${{ secrets.HOST_DNS_PROD_1 }}
            REMOTE_USER: ${{ secrets.EC2_USER }}
            TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh ec2 1
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST_DNS_PROD_1 }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                script: |
                sudo docker stop go_ec2_Docker_mainp || echo "No existing process found"
                sudo docker rm go_ec2_Docker_mainp || echo "No existing process found"
                sudo docker pull 2424833f/go_docker_main:latest
                sudo docker run --network=host -d -p 80:80 --name go_ec2_Docker_mainp 2424833f/go_docker_main:latest

      - name: Executing remote ssh commands ec2 2
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST_DNS_PROD_2 }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                sudo docker stop go_ec2_Docker_mainp || echo "No existing process found"
                sudo docker rm go_ec2_Docker_mainp || echo "No existing process found"
                sudo docker pull 2424833f/go_docker_main:latest
                sudo docker run --network=host -d -p 80:80 --name go_ec2_Docker_mainp 2424833f/go_docker_main:latest
                
      - name: Executing remote ssh commands ec2 3
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST_DNS_PROD_3 }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                sudo docker stop go_ec2_Docker_mainp || echo "No existing process found"
                sudo docker rm go_ec2_Docker_mainp || echo "No existing process found"
                sudo docker pull 2424833f/go_docker_main:latest
                sudo docker run --network=host -d -p 80:80 --name go_ec2_Docker_mainp 2424833f/go_docker_main:latest

      - name: Executing remote ssh commands ec2 4
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST_DNS_PROD_4 }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                sudo docker stop go_ec2_Docker_mainp || echo "No existing process found"
                sudo docker rm go_ec2_Docker_mainp || echo "No existing process found"
                sudo docker pull 2424833f/go_docker_main:latest
                sudo docker run --network=host -d -p 80:80 --name go_ec2_Docker_mainp 2424833f/go_docker_main:latest
                